name: Changesets Snapshot
description: A GitHub action to publish snapshot releases with Changesets
runs:
  using: 'node20'
  main: 'dist/index.js'
inputs:
  pre-publish:
    description: 'The command to run prior to the main publish script'
    required: false
  pre-version:
    description: 'The command to run prior to the main version script'
    required: false
outputs:
  published:
    description: A boolean value to indicate whether a publishing has happened or not
  publishedPackages:
    description: >
      A JSON array to present the published packages. The format is `[{"name": "@xx/xx", "version": "1.2.0"}, {"name": "@xx/xy", "version": "0.8.9"}]`
branding:
  icon: 'camera'
  color: 'blue'
